[tool.ruff]
line-length = 120
lint.ignore = ["E501"]
[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["F841"]
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests", "src"]
norecursedirs = [".env", "data", "maps", ".github", ".vscode"]
console_output_style = "count"
addopts = "--cov-branch --cov=palletjack --cov-report term --cov-report xml:cov.xml --instafail"
